feat: support ttl check and update ttl
kitex-contrib/registry-consul pull request #17
Opened 2024-12-02 15:03 UTC by nnothing1

- Support TTL check and auto update TTL after registering to Consul
- Add unit test
- fix #16

2024-12-02 15:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kitex-contrib/registry-consul?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kitex-contrib/registry-consul?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kitex-contrib/registry-consul?pullRequest=17) it.</sub>

2024-12-03 08:22 UTC, GuangmingLuo commented
@baiyutang 麻烦看看

2024-12-09 05:14 UTC, baiyutang requested changes

2024-12-09 05:14 UTC, baiyutang commented on consul_registry.go
> +	if ttl <= 1*time.Second {
这个参数校验可以放在更前边，放在注册之前去校验 Agent().ServiceRegister(svcInfo);

2024-12-09 05:14 UTC, baiyutang commented on consul_test.go
> +	list, _, err := consulClient.Health().Service(testSvcName, "", true, nil)
这里去获取服务实例列表，建议多等待几个 TTL 的周期，或者连续去校验几个 TTL 周期，证明更新是有效的。

2024-12-09 06:15 UTC, baiyutang commented on consul_registry.go
> +		if err := c.consulClient.Agent().UpdateTTL(c.opts.check.CheckID, "online", api.HealthPassing); err != nil {
另外还应该评估下 Deregister 时 是否有必要主动停止这里的 更新，如果 调用 Deregister 但是距离真正服务停止还有一段时间，是否会有时间空隙，然后客户端会获取到这个准备下线的实例，去请求却又请求不到 造成失败。这种可以评估一下。

2024-12-15 14:25 UTC, nnothing1 commented on consul_registry.go
> +		if err := c.consulClient.Agent().UpdateTTL(c.opts.check.CheckID, "online", api.HealthPassing); err != nil {
我感觉是有必要主动停止的，因为只要调用 ServiceDeregister(svcID) 成功后该实例就会从 consul 里注销，客户端无法获取该实例，同时 UpdateTTL 也会失败。为了避免可能的自行多次调用 Register 和 Deregister 的情况从而导致旧的更新 goroutine 没有停止，我个人觉得还是需要在 ServiceDeregister 成功后主动 cancel 掉这个 goroutine 。

2024-12-15 14:26 UTC, nnothing1 commented on consul_registry.go
> +	if ttl <= 1*time.Second {
done

2024-12-15 14:27 UTC, nnothing1 commented on consul_test.go
> +	list, _, err := consulClient.Health().Service(testSvcName, "", true, nil)
done

2024-12-19 02:17 UTC, merged